// Stage 20.1 — persistent world-state bridge.
// Stage 20 already owns the visual state of each structure. This module does
// not replace it: it adds persistence, regional noise, history and migration
// hooks while preserving every state/event/secret created by StructureManager.

class WorldStateSystem {
  constructor(world, structures, seed) {
    this.world = world;
    this.structures = structures;
    this.seed = seed >>> 0;
    this.history = [];
    this.discoveredRegions = new Set();
    this.regionNoise = new Map();
    this.currentStructure = null;
    this.currentRegion = null;
    this.entrySerial = 0;
    this._historyId = 1;
    this.onDiscover = null;
    this.onEnter = null;
    this.prepare();
  }

  prepare() {
    for (const s of this.structures.structures) {
      // StructureManager Stage 20 is authoritative. Only fill missing fields.
      s.state = s.state || 'intact';
      s.lootProfile = s.lootProfile || 'household';
      s.dangerLevel = s.dangerLevel ?? 1;
      s.ambientProfile = s.ambientProfile || s.style || 'generic';
      s.eventPool = Array.isArray(s.eventPool) ? s.eventPool : [];
      s.secretRooms = Array.isArray(s.secretRooms) ? s.secretRooms : [];
      s.powered = Boolean(s.powered);
      s.initialPower = Boolean(s.initialPower || s.powered);
      s.discovered = Boolean(s.discovered);
      s.visits = Number.isFinite(s.visits) ? s.visits : 0;
      s.alert = Number.isFinite(s.alert) ? s.alert : 0;
      s.lastNoiseLabel = s.lastNoiseLabel || '';
      s.lastNoiseRadius = s.lastNoiseRadius || 0;
      s.worldStateVersion = 2;
    }
    // Points generated by the content pass get an area automatically when the
    // builder did not explicitly assign one.
    for (const p of this.structures.points) {
      if (p.area) continue;
      const s = this.structureAt(p.tileX, p.tileY);
      if (s) p.area = s.name;
    }
  }

  structureAt(tileX, tileY = null) {
    if (typeof this.structures.structureAt === 'function') {
      const s = this.structures.structureAt(tileX, tileY, 2);
      if (s) return s;
    }
    const list = this.structures.structures.filter(s => {
      if (tileX < s.x - 2 || tileX > s.endX + 2) return false;
      if (tileY == null) return !s.underground;
      if (s.underground) {
        const top = s.y1 ?? s.yTop ?? s.groundY - 12;
        const bottom = s.y2 ?? s.yBottom ?? s.groundY + 4;
        return tileY >= top && tileY <= bottom;
      }
      return tileY <= s.groundY + 4;
    });
    if (!list.length) return null;
    list.sort((a,b) => Math.abs(tileX - (a.x+a.endX)/2) - Math.abs(tileX - (b.x+b.endX)/2));
    return list[0];
  }

  applyInitialPower(places) {
    if (!places) return;
    for (const s of this.structures.structures) {
      if (s.initialPower && typeof places.powerArea === 'function') places.powerArea(s.name);
      s.powered = Boolean(places.poweredAreas?.has(s.name));
    }
  }

  record(kind, data = {}) {
    const entry = { id: this._historyId++, kind, ...data };
    this.history.push(entry);
    if (this.history.length > 180) this.history.shift();
    return entry;
  }

  revealSecret(structure, reason = 'exploration') {
    if (!structure) return null;
    const secret = (structure.secretRooms || []).find(q => !(q.revealed || q.found || q.realized));
    if (!secret) return null;
    secret.revealed = true;
    secret.found = true;
    this.record('secret_revealed', {
      area: structure.name,
      secretId: secret.id || secret.kind || 'secret',
      secretKind: secret.kind || secret.label || 'hidden',
      reason
    });
    return secret;
  }

  onNoise(x, y, radius, label = 'ruído') {
    const tx = Math.floor(x / CONFIG.TILE);
    const ty = Math.floor(y / CONFIG.TILE);
    const region = this.world.region(Math.max(0, Math.min(CONFIG.WORLD_W - 1, tx)));
    const key = region.id;
    const weight = Math.max(.04, Math.min(6, radius / 230));
    const row = this.regionNoise.get(key) || { value: 0, tileX: tx, tileY: ty, label: '', region: region.name };
    row.value = Math.min(24, row.value + weight);
    row.tileX = tx;
    row.tileY = ty;
    row.label = label;
    row.region = region.name;
    this.regionNoise.set(key, row);

    const s = this.structureAt(tx, ty);
    if (s) {
      s.alert = Math.min(24, (s.alert || 0) + weight * 1.2);
      s.lastNoiseLabel = label;
      s.lastNoiseRadius = radius;
    }
  }

  noiseHotspot(minValue = .8) {
    let best = null;
    for (const [id, data] of this.regionNoise) {
      if (data.value < minValue) continue;
      if (!best || data.value > best.value) best = { id, ...data };
    }
    return best;
  }

  syncFromVisit(visit, player) {
    const c = player.center();
    const tx = Math.floor(c.x / CONFIG.TILE);
    const region = this.world.region(Math.max(0, Math.min(CONFIG.WORLD_W - 1, tx)));
    if (!this.discoveredRegions.has(region.id)) {
      this.discoveredRegions.add(region.id);
      this.record('region_discovered', { region: region.name, regionId: region.id, tileX: tx });
    }

    const structure = visit?.structure || this.structures.current || this.structureAt(tx, Math.floor(c.y / CONFIG.TILE));
    if (structure !== this.currentStructure) {
      this.currentStructure = structure;
      if (structure) {
        this.entrySerial++;
        this.record('structure_entered', { area: structure.name, state: structure.state, visit: structure.visits || 0, serial: this.entrySerial });
        if (visit?.fresh) {
          this.record('structure_discovered', { area: structure.name, state: structure.state, type: structure.type });
          this.onDiscover?.(structure);
        }
        this.onEnter?.(structure, Boolean(visit?.fresh));
      }
    }
    this.currentRegion = region.id;
  }

  update(dt, player, places, visit = null) {
    for (const [id, row] of this.regionNoise) {
      row.value = Math.max(0, row.value - dt * .035);
      if (row.value <= .01) this.regionNoise.delete(id);
    }
    for (const s of this.structures.structures) {
      s.alert = Math.max(0, (s.alert || 0) - dt * .02);
      if (places?.poweredAreas) s.powered = places.poweredAreas.has(s.name);
    }
    if (player) this.syncFromVisit(visit, player);
  }

  exportState() {
    return {
      version: 2,
      discoveredRegions: [...this.discoveredRegions],
      structures: this.structures.structures.map(s => ({
        name: s.name,
        state: s.state,
        discovered: Boolean(s.discovered),
        visits: s.visits || 0,
        powered: Boolean(s.powered),
        alert: s.alert || 0,
        secrets: (s.secretRooms || []).map(q => ({
          id: q.id || null, kind: q.kind || null,
          revealed: Boolean(q.revealed), found: Boolean(q.found), realized: Boolean(q.realized),
          resolved: Boolean(q.resolved), contentHook: q.contentHook ?? null
        }))
      })),
      history: this.history.slice(-140),
      regionNoise: [...this.regionNoise.entries()]
    };
  }

  importState(data, places = null) {
    if (!data || ![1,2].includes(data.version)) return false;
    this.discoveredRegions = new Set(data.discoveredRegions || []);
    const byName = new Map(this.structures.structures.map(s => [s.name, s]));
    for (const row of data.structures || []) {
      const s = byName.get(row.name);
      if (!s) continue;
      // accept any valid Stage 20 state instead of narrowing to the Stage 19 list
      if (typeof row.state === 'string') s.state = row.state;
      s.discovered = Boolean(row.discovered);
      s.visits = row.visits || 0;
      s.alert = row.alert || 0;
      if (places && row.powered && typeof places.powerArea === 'function') places.powerArea(s.name);
      const saved = row.secrets || [];
      for (const q of s.secretRooms || []) {
        const match = saved.find(v => (v.id && q.id === v.id) || (!v.id && v.kind && q.kind === v.kind));
        if (match) Object.assign(q, match);
      }
    }
    this.history = (data.history || []).slice(-140);
    this.regionNoise = new Map(data.regionNoise || []);
    return true;
  }
}
